<!-- Tableau des produits  -->
<h2 class="my_products">Mes produits</h2>
<table class="tableProducts">
  <thead class="tableProductsHead">
    <tr class="tableProductsHeadRow">
      <th scope="col tableProductsHeadColumn">ID</th>
      <th scope="col tableProductsHeadColumn">Titre</th>
      <th scope="col tableProductsHeadColumn">Description</th>
      <th scope="col tableProductsHeadColumn">Prix</th>
      <th scope="col tableProductsHeadColumn">Coefficient</th>
      <th scope="col tableProductsHeadColumn">Modifier</th>
      <th scope="col tableProductsHeadColumn">Supprimer</th>
    </tr>
  </thead>
  <tbody class="tableProductsMain">
    <?php foreach($aProducts as $oProductsTable) :?>
    <tr class="tableProductsMainRow">
      <th class="tableProductsMainHead" scope="row"><?= intval($oProductsTable -> getId())?></th>
      <td class="tableProductsMainColumn"><?= htmlspecialchars($oProductsTable -> getTitle())?></td>
      <td class="tableProductsMainColumn"><?= htmlspecialchars($oProductsTable -> getDescription())?></td>
      <td class="tableProductsMainColumn"><?= intval($oProductsTable -> getPrice())?></td>
      <td class="tableProductsMainColumn"><?= intval($oProductsTable -> getCoefficient())?></td>
      <td class="tableProductsMainIcon"><a href="index.php?action=edit_product&id=<?php echo intval($oProductsTable -> getId()) ?>"><ion-icon name="pencil-outline"></ion-icon</a></td>
      <td class="tableProductsMainIcon"><a href="index.php?action=delete_product&id=<?php echo intval($oProductsTable -> getId()) ?>"><ion-icon name="trash-outline"></ion-icon></a></td>
    </tr>
    <?php endforeach ?>
  </tbody>
</table>

<!-- Lien pour l'insertion de nouveau produit ou d'option  -->
<div><a href="index.php?action=insert_product">Insertion produit ou option</a></div>

<!-- Tableau des utilisateurs/clients -->
<h2 class="clientsTitle">Listing Clients</h2>
<table class="clientsTable">
  <thead class="clientsTableHead">
    <tr class="clientsTableHeadRow">
      <th scope="col clientsTableHeadColumn">ID</th>
      <th scope="col clientsTableHeadColumn">Nom</th>
      <th scope="col clientsTableHeadColumn">Prénom</th>
      <th scope="col clientsTableHeadColumn">Adresse</th>
      <th scope="col clientsTableHeadColumn">Code postale</th>
      <th scope="col clientsTableHeadColumn">Ville</th>
      <th scope="col clientsTableHeadColumn">Téléphone</th>
      <th scope="col clientsTableHeadColumn">Email</th>
      <th scope="col clientsTableHeadColumn">Login</th>
      <th scope="col clientsTableHeadColumn">Modifier</th>
      <th scope="col clientsTableHeadColumn">Supprimer</th>
    </tr>
  </thead>
  <tbody class="tableProductsMain">
    <?php foreach($aAllUsers as $oUsersTable) :?>
    <tr class="tableProductsMainRow">
      <th class="tableProductsMainHead" scope="row"><?= intval($oUsersTable -> getId())?></th>
      <td class="tableProductsMainColumn"><?= htmlspecialchars($oUsersTable -> getName())?></td>
      <td class="tableProductsMainColumn"><?= htmlspecialchars($oUsersTable -> getFirstname())?></td>
      <td class="tableProductsMainColumn"><?= htmlspecialchars($oUsersTable -> getAddress())?></td>
      <td class="tableProductsMainColumn"><?= htmlspecialchars($oUsersTable -> getPostalcode())?></td>
      <td class="tableProductsMainColumn"><?= htmlspecialchars($oUsersTable -> getCity())?></td>
      <td class="tableProductsMainColumn"><?= htmlspecialchars($oUsersTable -> getPhone())?></td>
      <td class="tableProductsMainColumn"><?= htmlspecialchars($oUsersTable -> getEmail())?></td>
      <td class="tableProductsMainColumn"><?= htmlspecialchars($oUsersTable -> getLogin())?></td>
      <td class="tableProductsMainIcon"><a href="#"><ion-icon name="pencil-outline"></ion-icon</a></td>
      <td class="tableProductsMainIcon"><a href="#"><ion-icon name="trash-outline"></ion-icon></a></td>
    </tr>
    <?php endforeach ?>
  </tbody>
</table>

<!-- Tableau des commandes -->
<h2 class="commandesTitle">Listing Commandes</h2>
<table class="commandesTable">
  <thead class="commandesTableHead">
    <tr class="commandesTableHeadRow">
      <th scope="col commandesTableHeadColumn">Numéro de Commande</th>
      <th scope="col commandesTableHeadColumn">Status</th>
      <th scope="col commandesTableHeadColumn">Total</th>
      <th scope="col commandesTableHeadColumn">Date</th>
      <th scope="col commandesTableHeadColumn">Details</th>
      <th scope="col commandesTableHeadColumn">Modifier</th>
      <th scope="col commandesTableHeadColumn">Supprimer</th>
    </tr>
  </thead>
  <tbody class="tableProductsMain">
    <?php foreach($aOrders as $oOrder) :?>
    <tr class="tableProductsMainRow">
      <th class="tableProductsMainHead" scope="row"><?= intval($oOrder -> getId())?></th>
      <td class="tableProductsMainColumn"><?= htmlspecialchars($oOrder -> getFlags())?></td>
      <td class="tableProductsMainColumn"><?= htmlspecialchars($oOrder -> getTotal())?></td>
      <td class="tableProductsMainColumn"><?= htmlspecialchars(date_format($oOrder -> getDateQuote(), 'Y/m/d H:i:s'))?></td>
      <td class="tableProductsMainColumn">A FAIRE (AFFICHAGE DU PANIER)</td>
      <td class="tableProductsMainIcon"><a href="#"><ion-icon name="pencil-outline"></ion-icon</a></td>
      <td class="tableProductsMainIcon"><a href="#"><ion-icon name="trash-outline"></ion-icon></a></td>
    </tr>
    <?php endforeach ?>
  </tbody>
</table>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
