<section class="edit-profile">
<h1>Modifier mon profil</h1>
        <form action="?action=edit_user" method="POST">
            <input type="hidden" name="id" value='' >
            <label for="name"><b>Nom</b></label>
                <input type="text" placeholder="Saissisez votre nom" name="name"><br>
            <label for="firstname"><b>Prénom</b></label>
                <input type="text" placeholder="Saissisez votre prénom" name="firstname"><br>
            <label for="address"><b>Adresse Postale</b></label>
                <input type="text" placeholder="Saissisez votre adresse postale" name="address"><br>
            <label for="postalcode"><b>Code Postal</b></label>
                <input type="text" placeholder="postalcode" name="postalcode"><br>
            <label for="city"><b>Ville</b></label>
                <input type="text" placeholder="city" name="city"><br>
            <label for="phone"><b>Téléphone</b></label>
                <input type="text" placeholder="Saissisez votre telephone" name="phone"><br>
            <label for="email"><b>Adresse e-mail</b></label>
                <input type="email" placeholder="Saissisez votre email" name="email"><br>
            <label for="login"><b>Nom d'utilisateur</b></label>
                <input type="text" placeholder="Enregistrer votre nom" name="login"><br>
            <label for="password"><b>Mot de passe</b></label>
                <input type="password" placeholder="mot de passe" name="password">
            <label for="confirmpassword"><b>Confirmation de mot de passe</b></label>
                <input type="password" placeholder=" confirmation de mot de passe" name="confirmpassword" required><br>
            <button type="submit" name="edit_profile"  id='edit_profile' value='EDI_PROFILE'>S'inscrire</button>
        </form> 
</section>