
    <footer class="footer-nav">
        <a class="nav-link" href="?action=#">Mentions Légales</a>
        <a class="nav-link" href="?action=#">Nos coordonnées</a>
        <a class="nav-link" href="index.php?action=products">Nos Produits</a>
        <a class="nav-link" href="?action=#">Nous contacter</a>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="./public/js/burgernav.js"></script>
    <script src="./public/js/products.js"></script>
    <script src="./public/js/product_description.js"></script>
    <script src="./public/js/panier.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    </body>
</html>