
<h1>Notre Histoire</h1>
<img class="avatar"src="./public/img/Fran_avatar.png" alt="avatar Françoise">
    <p>Lorem ipsum dolor sit amet. Eos fugit possimus vel culpa porro ut ipsa voluptatum. Id modi recusandae aut deleniti aspernatur non perspiciatis eveniet ea libero dolorum. Et omnis omnis sed consectetur commodi est consectetur saepe et inventore enim. Est sapiente dolorem qui nisi sint hic sint eveniet.

    In voluptatem molestias et dolor distinctio et ratione eveniet et repellat rerum ab repellendus recusandae vel blanditiis corporis. Vel galisum culpa ut repellendus ipsum et fugit accusantium ut doloribus voluptate non pariatur numquam qui similique quibusdam. Et quia explicabo et molestias officiis voluptatem exercitationem. </p>
