
<!-- Vue de ma formulaire de l'admin pour l'insertion -->

<h2>Insertion des produits</h2>
<section>
  <form  method="POST">
    <input type="hidden" name="token" value='<?php echo $token ?>' >
    <fieldset>
      <legend>Forme générale</legend>
      <label for="modelGeneralCategory"><b>Categorie</b></label>
      <select name="modelGeneralCategory" id="modelGeneralCategory">
        <?php foreach ($aCategories as $oCategory) { ?>
          <option value="<?php echo $oCategory->getId() ?>"><?php echo $oCategory->getTitle() ?></option>
        <?php } ?>
      </select><br>
      <label for="modelGeneralTitle"><b>Titre</b></label>
        <input id="modelGeneralTitle" type="text" placeholder="title" name="modelGeneralTitle" ><br>
      <label for="modelGeneralDescription"><b>Description</b></label>
        <input id="modelGeneralDescription" type="text" placeholder="description" name="modelGeneralDescription" ><br>
      <label for="modelGeneralPrice"><b>Prix</b></label>
        <input id="modelGeneralPrice" type="text" placeholder="price" name="modelGeneralPrice" ><br>
      <label for="modelGeneralCoefficient"><b>Coefficient</b></label>
        <input id="modelGeneralCoefficient" type="text" placeholder="coefficient" name="modelGeneralCoefficient" ><br>
    </fieldset>
  <button type="submit" name="submit"  id='submit' value='submit'>Enregistrer</button>
</section>