<div>
    <section>
        <h1>Connexion</h1>
        <form action="?action=login" method="POST">
            <input type="hidden" name="id">
            <label for="loginoremail"><b>Login ou Adresse e-mail</b></label>
                <input type="text" placeholder="Saissisez votre email" name="loginoremail" id="loginoremail" required><br>
            <label for="password"><b>Mot de passe</b></label>
                <input type="password" placeholder="mot de passe" name="password" id="password" required><br>
            <button type="submit" name="submit" id='submit' value='LOGIN'>Connexion</button>
            <?php if (isset($error)): ?>
                <p><?=$error;?></p>
            <?php endif; ?>
        </form> 
    </section>
</div>