<h1>Actualités</h1>
<article>
    <img src="./public/img/news_pictures.jpg" alt="matiere premiere robe de mariee">
    <h2>Robes de mariée en cours de confection</h2>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. In ut excepturi molestias, est eos laudantium neque vitae officia assumenda ratione voluptate consequatur! Adipisci blanditiis impedit rerum eaque debitis expedita ullam.</p>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iste, nemo ab quisquam, maiores possimus, culpa est assumenda soluta cupiditate quas quidem earum itaque vero harum? Corporis expedita ab in dolores.</p>
</article>
