<link rel="stylesheet" href="./public/css/panier.css">
<h2>Votre Panier</h2>
<section class="cartProducts">
    <p class="cartProducts-info"></p>
    <table id="cartProducts-item">
        <tr>
            <th>Article</th>
            <th>Taille</th>
            <th>Prix</th>
            <th>Quantité</th>
            <th></th>
        </tr>
        <!-- <tr class="cartProductsItem">
            <td class="cartProductsItemTitle">Mona</td>
            <td class="cartProductsItemSize">34</td>
            <td class="cartProductsItemPrice">1099€</td>
            <td class="cartProductsItemQuantity">1</td>
            <td class="cartProductsItemRemove">Supprimer</td>
        </tr> -->
    </table>
    <?php if ($oUserSession->isConnected()) { ?>
        <button class="cartProducts-validate">Commander</button>
    <?php } else { ?>
        <a class="cartProducts-signin" href="?action=login">Veuillez vous connecter pour Commander.</a>
    <?php } ?>
</section>