<h2>Votre Panier</h2>
<section class="cartProducts">
    <p class="cartProductsInfo"></p>
    <table>
        <thead>
            <tr>
                <th>Article</th>
                <th>Taille</th>
                <th>Prix</th>
                <th>Quantité</th>
                <th></th>
            </tr>
        </thead>
        <tbody id="cartProductsList"></tbody>
    </table>
    <?php if ($oUserSession->isConnected()) { ?>
        <button class="cartProductsValidate">Commander</button>
    <?php } else { ?>
        <a class="cartProductsSignin" href="?action=login">Veuillez vous connecter pour Commander.</a>
    <?php } ?>
</section>