<link rel="stylesheet" href="./public/css/panier.css">
<h2>Votre Panier</h2>
<section class="cartProducts">
    <table>
        <tr>
            <th>Article</th>
            <th>Taille</th>
            <th>Prix</th>
            <th>Quantité</th>
        </tr>
        <tr class="cartProductsItem">
            <td class="cartProductsItemTitle">Mona</td>
            <td class="cartProductsItemSize">34</td>
            <td class="cartProductsItemPrice">1099€</td>
            <td class="cartProductsItemQuantity">1</td>
        </tr>
        <tr class="cartProductsItem">
            <td class="cartProductsItemTitle">Lisa</td>
            <td class="cartProductsItemSize">36</td>
            <td class="cartProductsItemPrice">3099€</td>
            <td class="cartProductsItemQuantity">1</td>
        </tr>
    </table>
</section>