<link rel="stylesheet" href="./public/css/product_description.css">

<h1>Description des produits</h1>
<div class="viewContainer">
    <div class="card viewContainerProductItem">  
        <img class="card viewContainerProductItemImage" src="<?php echo htmlspecialchars(DIR_PROD_IMG. '/' . $oProductItem->getImage())?>" alt="wedding dress">
    </div>
    <div>
        <h2><?php echo htmlspecialchars($oProductItem->getTitle()) ?></h2>
        <p><?php echo htmlspecialchars($oProductItem->getDescription()) ?></p>
        <?php foreach ($aProductSize as $oProdSize) { ?>
            <p>
            <?php echo htmlspecialchars($oProdSize->getSizeEu()) ?></p>
        <?php } ?>
        
        <p class="price"><?php echo htmlspecialchars($oProductItem->getPrice()) ?> €</p>
    </div>
</div>