<link rel="stylesheet" href="./public/css/products.css">

<div class="product">
    <section class="productMain">
        <h1 class="productMainTitle">Mes produits</h1>
        <!-- Partie recherche de produits -->
        <div class="productSearch"> 
            <!-- <div class="flexCenter"> -->
            <div><i class="fa-light fa-person-dress"></i></div>
            <div><input id="searchFinder" class="searchProductFinder" type="text" placeholder="Trouvez votre robe"></div>
            <div id="search" class="productSearchBar">
               
            </div>
        </div>
        </div class="productItem">
            <!-- Mise en place des produits de la BDD  -->
            <form class="productItemForm" action="?action=product" method="POST">
                <h2 class="productItemFormTitle">Coupe générale de la robe</h2>
            <?php
            foreach ($aProducts as $ProductChoiceItem) { ?>
                <label for="princess"><b></b></label>
                <img class="productItemFormImage" src="./public/img/img_products/Lola_Dress.jpg" alt="Wedding_Dress_Lola"><br>
                <div class="productItemFormButton">
                <input class="productItemFormButtonRadio" type="radio" placeholder="princesse" name="princess" required><?php echo htmlspecialchars($ProductChoiceItem->getTitle())?> <br>
            <?php } ?>
                <!-- <label for="bohemia"><b></b></label>
                    <img src="./public/img//img_products/Lola_Dress.jpg" alt="Wedding_Dress_Lola"><br>
                    <div class="productButton">
                    <input type="radio" placeholder="boheme" name="bohemia" required>Coupe Bohème-Champêtre<br>
                    </div>
                <label for="empire"><b></b></label>
                    <img src="./public/img//img_products/Lola_Dress.jpg" alt="Wedding_Dress_Lola"><br>
                    <div class="productButton">
                    <input type="radio" placeholder="empire" name="bohemia" required>Coupe Bohème-Champêtre<br>
                    </div> -->
            </form>   
        </div>
    </section>
    <aside class="news">
        <h2>Nouveautés</h2>
        <p></p>
        <h2>Lieux de mariage</h2>
        <div class="card eventsLocation">  
            <img class="eventsLocationImage" src="./public/img/img_events/chateau-pioline.jpg" alt="chateau pioline">
            <h3 class="eventsLocationTitle">Château Pioline</h3>
            <!-- <p class="price">1240€</p> -->
            <a href="https://www.chateaudelapioline.com/fr/" target="_blank" class="eventsLocationTitleButton">En savoir plus</a>
        </div>
    </aside>
</div>