<link rel="stylesheet" href="./public/css/product_description.css">

<h1>Description des produits</h1>
<div class="viewContainer">
    <div class="card viewContainerProductItem">  
        <img class="card viewContainerProductItemImage" src="<?php echo htmlspecialchars(DIR_PROD_IMG. '/' . $oProductItem->getImage())?>" alt="wedding dress">
    </div>
    <div class="viewContainerProductDescription" >
        <div class="viewContainerProductDescriptionPopup">
            <p>L'article à été ajouter avec succès à votre Panier !</p>
        </div>
        <h2 class="viewContainerProductDescriptionTitle">
        <?php echo htmlspecialchars($oProductItem->getTitle()) ?></h2>
        <p class="viewContainerProductDescriptionContent"><?php echo htmlspecialchars($oProductItem->getDescription()) ?></p>
        <div class="viewContainerProductDescriptionSize">
            <?php foreach ($aProductSize as $oProdSize) { ?>
                <p class="viewContainerProductDescriptionSizeContent"><?php echo htmlspecialchars($oProdSize->getSizeEu()) ?> (<?php echo htmlspecialchars($oProdSize->getSizeUs()) ?>)</p>
            <?php } ?>
        </div>
        <p class="viewContainerProductDescriptionPrice"><?php echo htmlspecialchars($oProductItem->getPrice()) ?> €</p>
        <button class="viewContainerProductDescriptionButton">Ajouter un panier</button>
    </div>
</div>