<div class="product">
    <section class="productMain">
        <h1 class="productMainTitle">Mes produits</h1>
        <!-- Partie recherche de produits -->
        <div class="productSearch"> 
            <!-- <div class="flexCenter"> -->
            <div><i class="fa-light fa-person-dress"></i></div>
            <div><input id="searchFinder" class="searchProductFinder" type="text" placeholder="Trouvez votre robe"></div>
            <div id="search" class="productSearchBar">
               
            </div>
        </div>
        </div class="productItem">
            <!-- Mise en place des produits de la BDD  -->
            <form class="productItemForm" action="?action=product" method="POST">
                <h2 class="productItemFormTitle">Nos robes de mariée</h2>
                <?php foreach ($aProducts as $oProduct) { ?>
                    <div class="productItemFormContainer">
                        <img class="productItemFormContainerImage" 
                        src="<?php echo htmlspecialchars(DIR_PROD_IMG. '/' . $oProduct->getImage())?>" 
                        alt="<?php echo htmlspecialchars($oProduct->getDescription())?>">
                        <h4 class="productItemFormContainerTitle"><?php echo htmlspecialchars($oProduct->getTitle())?></h4>
                        <p class="productItemFormContainerPrice"><?php echo $oProduct->getPrice() ?> €</p>
                        <a class="productItemFormContainerLink" href="?action=product_description&id=<?php echo $oProduct->getId() ?>">Voir +</a>
                    </div>
                <?php } ?>
            </form>   
        </div>
    </section>
    <!-- <aside class="news">
        <h2>Nouveautés</h2>
        <p></p>
        <h2>Lieux de mariage</h2>
        <div class="card eventsLocation">  
            <img class="eventsLocationImage" src="./public/img/img_events/chateau-pioline.jpg" alt="chateau pioline">
            <h3 class="eventsLocationTitle">Château Pioline</h3>
            <p class="price">1240€</p> -->
            <!-- <a href="https://www.chateaudelapioline.com/fr/" target="_blank" class="eventsLocationTitleButton">En savoir plus</a>
        </div>
    </aside> -->
</div>