<section>
    <h1>Inscription</h1>
    <form action="?action=registration" method="POST">
        <input type="hidden" name="id" value='' >
        <label for="name"><b>Nom</b></label>
        <input type="text" placeholder="Saissisez votre nom" name="name" required>

        <label for="firstname"><b>Prénom</b></label>
        <input type="text" placeholder="Saissisez votre prénom" name="firstname" required>

        <label for="address"><b>Adresse Postale</b></label>
        <input type="text" placeholder="Saissisez votre adresse postale" name="address" required>

        <label for="postalcode"><b>Code Postal</b></label>
        <input type="text" placeholder="postalcode" name="postalcode" required>

        <label for="city"><b>Ville</b></label>
        <input type="text" placeholder="city" name="city" required>

        <label for="phone"><b>Téléphone</b></label>
        <input type="text" placeholder="Saissisez votre telephone" name="phone" maxlength="10" required>

        <label for="email"><b>Adresse e-mail</b></label>
        <input type="email" placeholder="Saissisez votre email" name="email" required>

        <label for="login"><b>Nom d'utilisateur</b></label>
        <input type="text" placeholder="Enregistrer votre nom" name="login" required>

        <label for="password"><b>Mot de passe</b></label>
        <input type="password" placeholder="mot de passe" name="password" required>

        <label for="confirmpassword"><b>Confirmation de mot de passe</b></label>
        <input type="password" placeholder=" confirmation de mot de passe" name="confirmpassword" required>    

        <button type="submit" name="registration"  id='submit' value='REGISTRATION'>S'inscrire</button>
    </form> 
</section>
