<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content='<?php echo $sContent ?? 'Site internet de robes de mariée en précommande éco-responsable' ?>'> 
    <title><?php echo $sTitle ?? 'Robes de mariée en précommande éco-responsable'?></title>


    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lovers+Quarrel&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Calligraffitti&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Quattrocento+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="./public/css/responsive.css">
    <link rel="stylesheet" href="./public/css/wedding.css">
    <?php if (file_exists(__DIR__ . '/../public/css/' . $sContent . '.css')) { ?>
        <link rel="stylesheet" href="./public/css/<?php echo $sContent ?>.css">
    <?php } ?>
</head>
<body>

    <?php
        include_once VIEWS_DIR . '/header.phtml';
    ?>

    <main>
        <?php
            include_once VIEWS_DIR . '/' . $sContent . '.phtml';
        ?>
    </main>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<?php
include_once VIEWS_DIR . '/footer.phtml';?>
